CREATE TABLE `qb_dianping_claim` (
  `cid` mediumint(7) NOT NULL auto_increment,
  `id` mediumint(7) NOT NULL default '0',
  `uid` mediumint(7) NOT NULL default '0',
  `username` varchar(32) NOT NULL default '',
  `posttime` int(10) NOT NULL default '0',
  `yz` tinyint(1) NOT NULL default '0',
  `company_name` varchar(50) NOT NULL default '',
  `company_man` varchar(20) NOT NULL default '',
  `company_license` varchar(50) NOT NULL default '',
  `contact_man` varchar(30) NOT NULL default '',
  `contact_mob` varchar(15) NOT NULL default '',
  `contact_tel` varchar(20) NOT NULL default '',
  `contact_email` varchar(30) NOT NULL default '',
  `pic_license` varchar(100) NOT NULL default '',
  `pic_idcard` varchar(100) NOT NULL default '',
  `cuid` mediumint(7) NOT NULL default '0',
  `city_id` mediumint(7) NOT NULL default '0',
  `about` text NOT NULL,
  `check_reason` text NOT NULL,
  PRIMARY KEY  (`cid`),
  KEY `id` (`id`),
  KEY `yz` (`yz`),
  KEY `city_id` (`city_id`)
) TYPE=MyISAM AUTO_INCREMENT=1;